[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "cd .. && npm install",
  "cd .. && npm run build",
  "cd server && npm install"
]

[phases.build]
cmds = []

[start]
cmd = "node index.js"

